koboker_5:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_1
    pid: {p: 5, i: 0, d: 0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_2
    pid: {p: 5, i: 0, d: 0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_3
    pid: {p: 5, i: 0, d: 0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_4
    pid: {p: 5, i: 0, d: 0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_5
    pid: {p: 5, i: 0, d: 0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_6
    pid: {p: 5, i: 0, d: 0}
